apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizlet-backend
  labels:
    app: quizlet-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizlet-backend
  template:
    metadata:
      labels:
        app: quizlet-backend
    spec:
      containers:
      - name: quizlet-backend
        image: quizlet-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://quizuser:quizpass@quizlet-postgres:5432/quizdb"
        # Add readiness and liveness probes
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10