apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizlet-frontend
  labels:
    app: quizlet-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizlet-frontend
  template:
    metadata:
      labels:
        app: quizlet-frontend
    spec:
      containers:
      - name: quizlet-frontend
        image: quizlet-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: quizlet-frontend
spec:
  type: NodePort
  selector:
    app: quizlet-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000