name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy Quizlet app to Minikube
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.8.0
      with:
        minikube version: 'v1.37.0'
        kubernetes version: 'v1.28.0'
        driver: docker
        
    - name: Verify cluster
      run: kubectl get pods -A
      
    - name: Build backend image
      run: |
        eval $(minikube -p minikube docker-env)
        docker build -f ./backend/Dockerfile -t quizlet-backend:latest ./backend
        
    - name: Build frontend image
      run: |
        eval $(minikube -p minikube docker-env)
        docker build -f ./frontend/Dockerfile -t quizlet-frontend:latest ./frontend
        
    - name: Verify images
      run: |
        eval $(minikube -p minikube docker-env)
        docker images | grep quizlet
        
    - name: Deploy PostgreSQL
      run: kubectl apply -f k8s/postgres-deployment.yaml
      
    - name: Wait for PostgreSQL
      run: |
        kubectl wait --for=condition=ready pod -l app=quizlet-postgres --timeout=120s
        
    - name: Initialize database
      run: |
        sleep 20
        if [ -f "./backend/init_db.sql" ]; then
          echo "Initializing database with init script..."
          kubectl cp ./backend/init_db.sql quizlet-postgres-$(kubectl get pods -l app=quizlet-postgres -o jsonpath='{.items[0].metadata.name}'):/tmp/init_db.sql
          kubectl exec deployment/quizlet-postgres -- psql -U quizuser -d quizdb -f /tmp/init_db.sql
        else
          echo "No init_db.sql found, skipping database initialization"
        fi
        
    - name: Deploy backend
      run: kubectl apply -f k8s/backend-deployment.yaml
      
    - name: Deploy frontend
      run: kubectl apply -f k8s/frontend-deployment.yaml
      
    - name: Wait for deployments
      run: |
        kubectl wait --for=condition=available deployment/quizlet-backend --timeout=120s
        kubectl wait --for=condition=available deployment/quizlet-frontend --timeout=120s
        
    - name: Test services
      run: |
        echo "Backend service:"
        minikube service quizlet-backend --url || true
        echo "Frontend service:"
        minikube service quizlet-frontend --url || true
        
    - name: Show status
      run: |
        kubectl get all
        minikube service list